import React,{useState} from 'react';
import {Text,TextInput,View,Switch} from 'react-native';
import {router} from 'expo-router';
import * as Picker from 'expo-image-picker';
import {SignIn} from '../src/components/sign-in';
import {z} from 'zod';
import {POLICY_VERSION} from '@stylist/contracts';
import {Page,Button,Card,ErrorText,Busy,styles} from '../src/components/ui';
import {useSession} from '../src/state/session';
import {useAnalysis} from '../src/state/analysis-context';
import {appleSignIn,configured} from '../src/services/auth';
import {api} from '../src/services/api';
import {trackTemporary} from '../src/services/images';
const chips=['Does this outfit work?','What would you change?','Make this look more polished.','Does this work for a date?'];
export default function Home(){
 const {session,bootstrap,loading,error:sessionError,refresh}=useSession();const {state,setPrompt,prepare,cancel}=useAnalysis();const [adult,setAdult]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
 if(loading)return <Page title="Personal Stylist"><Busy text="Preparing your private workspace…"/></Page>;
 if(!session||!bootstrap?.consentAccepted)return <Page title="A fresh eye on your outfit."><Text style={styles.text}>A considered second opinion, with practical changes you can try. For adults in our invited iPhone beta.</Text><Card><Text style={styles.heading}>Your photo, one assessment</Text><Text style={styles.text}>Your photo and optional prompt are sent to our hosting and AI providers for this assessment. We do not save photos or unsaved reports in application storage. Provider processing and retention follow the beta privacy policy.</Text><Text style={styles.text}>History contains only text reports you choose to save. Cancellation cannot undo processing that already started.</Text></Card><View style={styles.row}><Switch accessibilityLabel="I am 18 or older" value={adult} onValueChange={setAdult}/><Text style={styles.text}>I am 18 or older</Text></View><View style={styles.row}><Switch accessibilityLabel="I consent to AI photo processing" value={consent} onValueChange={setConsent}/><Text style={styles.text}>I consent to this AI processing</Text></View><Text style={styles.muted}>Policy version {POLICY_VERSION}. You can withdraw consent in Settings.</Text>{!configured&&<ErrorText message="Add your public Supabase configuration to open the beta."/>}<ErrorText message={error??sessionError}/>{session?<Button title="Accept and continue" disabled={busy||!adult||!consent} onPress={()=>void run(async()=>{await api('/consents',z.object({accepted:z.boolean()}),{method:'POST',body:{policyVersion:POLICY_VERSION,accepted:true,adultConfirmed:true}});await refresh();})}/>:<SignIn disabled={busy||!adult||!consent} onApple={()=>void run(async()=>{await appleSignIn();await api('/consents',z.object({accepted:z.boolean()}),{method:'POST',body:{policyVersion:POLICY_VERSION,accepted:true,adultConfirmed:true}});await refresh();})} onLocal={login=>void run(async()=>{await login();await api('/consents',z.object({accepted:z.boolean()}),{method:'POST',body:{policyVersion:POLICY_VERSION,accepted:true,adultConfirmed:true}});await refresh();})}/>}{session&&<Button title="Settings" secondary onPress={()=>router.push('/settings')}/>}</Page>;
 const select=async()=>{const prompt=state.prompt;await cancel();setPrompt(prompt);const picked=await Picker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,quality:1,exif:false});if(picked.canceled)return;const photo=picked.assets[0];await trackTemporary(photo.uri);const outcome=await prepare(photo);if(outcome.status==='success')router.push('/review');else if(outcome.status==='failure')throw new Error(outcome.message);};
 return <Page title="What are you wearing?"><Text style={styles.muted}>OUTFIT · {process.env.EXPO_PUBLIC_ENVIRONMENT??'local'} beta{bootstrap.analysisMode==='mock'?' · MOCK — sample feedback':''}</Text><Text style={styles.text}>Add a photo for an overall assessment. A question is optional.</Text><Card><Text style={styles.heading}>A little perspective.</Text><Text style={styles.text}>Frame the outfit clearly, in natural light. Include shoes when you want feedback on the whole look.</Text><Button title="Take a photo" disabled={busy} onPress={()=>void run(async()=>{const prompt=state.prompt;await cancel();setPrompt(prompt);router.push('/camera');})}/><Button title="Choose a photo" secondary disabled={busy} onPress={()=>void run(select)}/></Card><TextInput accessibilityLabel="Optional outfit question" style={styles.input} multiline maxLength={1000} placeholder="Anything you’d like me to consider? (optional)" value={state.prompt} onChangeText={setPrompt}/><View style={{gap:8}}>{chips.map(chip=><Button key={chip} title={chip} secondary onPress={()=>setPrompt(chip)}/>)}</View><Text style={styles.muted}>{bootstrap.dailyQuotaExempt?'Unlimited daily analyses · test account':`${bootstrap.remainingQuota} of 3 daily analyses remaining.`}{!bootstrap.betaAccess?' Your invitation is awaiting activation.':''}{!bootstrap.features.outfit?' Analysis is currently paused.':''}</Text><ErrorText message={error??sessionError}/><View style={styles.row}><Button title="Saved reports" secondary onPress={()=>router.push('/history')}/><Button title="Settings" secondary onPress={()=>router.push('/settings')}/></View></Page>;
}
