import React,{useEffect,useRef,useState} from 'react';
import {Image,Text,TextInput} from 'react-native';
import {router} from 'expo-router';
import {Page,Button,Busy,ErrorText,styles} from '../src/components/ui';
import {useAnalysis} from '../src/state/analysis-context';
import {useSession} from '../src/state/session';
export default function Review(){const {state,setPrompt,submit,cancel}=useAnalysis();const {bootstrap,error:sessionError,refresh}=useSession();const [refreshing,setRefreshing]=useState(false);const moving=useRef(false);useEffect(()=>()=>{if(!moving.current)void cancel().catch(()=>{});},[]);const photo=state.prepared;
 const blocked=!bootstrap?'Account access could not be checked. Refresh access to try again.':!bootstrap.consentAccepted?'Accept AI-processing consent on the home screen to continue.':!bootstrap.betaAccess?'Your beta invitation is awaiting activation.':!bootstrap.dailyQuotaExempt&&bootstrap.remainingQuota<=0?'You have used all 3 daily analyses. The allowance resets at midnight UTC. Requests already sent, including retakes or interrupted assessments, may count.':!bootstrap.features.outfit?'Analysis is currently unavailable. Refresh access to check again.':null;
 return <Page title="Ready for a second opinion?">{state.status==='preparing'?<Busy text="Preparing and reducing your photo…"/>:photo?<Image accessibilityLabel="Outfit photo preview" source={{uri:photo.uri}} style={styles.photo}/>:<Text style={styles.text}>Choose a new photo to continue.</Text>}<ErrorText message={state.error}/><TextInput accessibilityLabel="Optional outfit question" style={styles.input} multiline maxLength={1000} value={state.prompt} onChangeText={setPrompt} placeholder="Your question (optional)"/><Text style={styles.muted}>Include as much of the outfit as possible. Only this prepared photo is uploaded.</Text>{bootstrap&&<Text style={styles.muted}>{bootstrap.dailyQuotaExempt?'Unlimited daily analyses · test account':`${bootstrap.remainingQuota} of 3 daily analyses remaining.`}</Text>}<ErrorText message={sessionError??null}/><ErrorText message={blocked}/><Button title="Analyse outfit" disabled={!photo||!['ready','failed'].includes(state.status)||!!blocked||refreshing} onPress={()=>{moving.current=true;void submit();router.replace('/processing');}}/>{blocked&&<Button title={refreshing?'Checking access…':'Refresh access'} secondary disabled={refreshing} onPress={()=>{setRefreshing(true);void refresh().catch(()=>{}).finally(()=>setRefreshing(false));}}/>}<Button title="Retake or choose another" secondary onPress={()=>{moving.current=true;void cancel().then(()=>router.replace('/'));}}/></Page>;
}
