import React,{useState} from 'react';
import {Text,View} from 'react-native';
import type {OutfitReport} from '@stylist/contracts';
import {Card,Button,styles} from './ui';
type Props={report:OutfitReport;onSuggestionFeedback?:(index:number,helpful:boolean)=>Promise<void>};
export function ReportView({report,onSuggestionFeedback}:Props){
 const [expanded,setExpanded]=useState(false),[feedback,setFeedback]=useState<Record<number,boolean>>({}),[sending,setSending]=useState<Record<number,boolean>>({});
 const send=async(index:number,helpful:boolean)=>{if(!onSuggestionFeedback)return;setSending(current=>({...current,[index]:true}));try{await onSuggestionFeedback(index,helpful);setFeedback(current=>({...current,[index]:helpful}));}finally{setSending(current=>({...current,[index]:false}));}};
 return <><Card><Text accessibilityRole="header" style={styles.heading}>{report.verdict==='works_well'?'Works well':report.verdict==='could_improve'?'Could improve':'Not enough visible detail to rate'}</Text><Text accessibilityLabel={report.overallScore===null?'Rating unavailable':`Rating ${report.overallScore} out of 10`} style={styles.title}>{report.overallScore===null?'Unrated':`${report.overallScore} / 10`}</Text><Text style={styles.text}>{report.summary}</Text>{report.status==='partial'&&<Text style={styles.muted}>Partial assessment · some details could not be assessed.</Text>}</Card>{report.strengths.length>0&&<Text style={styles.heading}>What works</Text>}{report.strengths.map((s,i)=><Text key={i} style={styles.text}>• {s}</Text>)}{report.suggestions.length>0&&<Text style={styles.heading}>Try this</Text>}{report.suggestions.map((s,i)=><Card key={i}><Text style={styles.muted}>{i===0?'Best next move':'Another option'}</Text><Text style={styles.muted}>{s.observation}</Text><Text style={styles.heading}>{s.action}</Text><Text style={styles.text}>{s.reason}</Text>{onSuggestionFeedback&&(i in feedback?<Text accessibilityLiveRegion="polite" style={styles.muted}>{feedback[i]?'Marked helpful':'Marked not for me'}</Text>:<View style={styles.row}><Button title="Helpful" accessibilityLabel={`Helpful, suggestion ${i+1}`} secondary disabled={sending[i]===true} onPress={()=>void send(i,true)}/><Button title="Not for me" accessibilityLabel={`Not for me, suggestion ${i+1}`} secondary disabled={sending[i]===true} onPress={()=>void send(i,false)}/></View>)}</Card>)}{report.limitations.map((s,i)=><Text key={i} style={styles.muted}>{s}</Text>)}<Button title={expanded?'Hide criteria':'Explore the criteria'} secondary onPress={()=>setExpanded(!expanded)}/>{expanded&&report.criteria.map(c=><View key={c.id} style={styles.card}><Text style={styles.heading}>{c.id[0].toUpperCase()+c.id.slice(1)} · {!c.applicable?'Not applicable':c.score===null?'Not visible':`${c.score} / 5`}</Text><Text style={styles.text}>{c.observation}</Text><Text style={styles.muted}>{c.explanation}</Text></View>)}</>;
}
