import React from 'react';
import {Pressable,Text,ScrollView,StyleSheet,View,ActivityIndicator} from 'react-native';
import {theme} from '../theme/tokens';
export const styles=StyleSheet.create({page:{flex:1,backgroundColor:theme.colors.background},content:{padding:24,gap:18,paddingBottom:60},title:{fontSize:34,fontWeight:'600',color:theme.colors.ink},heading:{fontSize:23,fontWeight:'600',color:theme.colors.ink},text:{fontSize:17,lineHeight:25,color:theme.colors.ink},muted:{fontSize:15,lineHeight:22,color:theme.colors.muted},card:{backgroundColor:theme.colors.surface,borderRadius:18,padding:20,gap:12,borderWidth:1,borderColor:theme.colors.line},button:{minHeight:50,borderRadius:14,paddingVertical:14,paddingHorizontal:18,backgroundColor:theme.colors.accent,alignItems:'center',justifyContent:'center'},buttonText:{color:'white',fontSize:17,fontWeight:'600',textAlign:'center'},input:{borderWidth:1,borderColor:theme.colors.muted,borderRadius:14,padding:16,fontSize:17,color:theme.colors.ink,backgroundColor:'white',minHeight:54},row:{flexDirection:'row',flexWrap:'wrap',gap:10},error:{color:theme.colors.error,fontSize:16,lineHeight:24},photo:{width:'100%',height:360,borderRadius:18,resizeMode:'contain'}});
export function Page({title,children}:{title:string;children:React.ReactNode}){return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text accessibilityRole="header" style={styles.title}>{title}</Text>{children}</ScrollView>;}
export function Button({title,onPress,disabled=false,secondary=false,accessibilityLabel=title}:{title:string;onPress:()=>void;disabled?:boolean;secondary?:boolean;accessibilityLabel?:string}){return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[styles.button,secondary&&{backgroundColor:theme.colors.muted},{opacity:disabled?0.5:pressed?0.8:1}]}><Text style={styles.buttonText}>{title}</Text></Pressable>;}
export function Card({children}:{children:React.ReactNode}){return <View style={styles.card}>{children}</View>;}
export function ErrorText({message}:{message:string|null}){return message?<Text accessibilityRole="alert" style={styles.error}>{message}</Text>:null;}
export function Busy({text}:{text:string}){return <View style={{gap:14}}><ActivityIndicator color={theme.colors.accent} size="large"/><Text accessibilityLiveRegion="polite" style={styles.text}>{text}</Text></View>;}
