import React from 'react';
import {render,screen,fireEvent} from '@testing-library/react-native';
import {ReportView} from '../components/report';
import {criterionIds,type OutfitReport} from '@stylist/contracts';
const report:OutfitReport={schemaVersion:1,runId:'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',status:'partial',summary:'The visible layers work together.',overallScore:null,verdict:null,criteria:criterionIds.map(id=>({id,applicable:id!=='intent',score:null,observation:'This detail is obscured.',explanation:'Use a wider frame.'})),strengths:['Visible colours relate well.'],suggestions:[],limitations:['Shoes are outside the frame.'],versions:{agent:'1',skill:'1',rubric:'1',model:'mock'}};
it('announces unavailable rating in text and expands criteria',()=>{render(<ReportView report={report}/>);expect(screen.getByLabelText('Rating unavailable')).toBeTruthy();expect(screen.getByText('Not enough visible detail to rate')).toBeTruthy();fireEvent.press(screen.getByRole('button',{name:'Explore the criteria'}));expect(screen.getByText('Intent · Not applicable')).toBeTruthy();});

it('hides empty strengths and suggestions for saved reports',()=>{render(<ReportView report={{...report,strengths:[]}}/>);expect(screen.queryByText('What works')).toBeNull();expect(screen.queryByText('Try this')).toBeNull();});

it('labels ranked suggestions and keeps feedback state independent',async()=>{const onFeedback=jest.fn().mockResolvedValue(undefined);render(<ReportView report={{...report,suggestions:[{kind:'swap',observation:'Formal shoes compete.',action:'Use a less formal shoe shape.',reason:'Matches the relaxed layers.'},{kind:'care',observation:'Visible crease.',action:'Steam the layer.',reason:'Cleans the line.'},{kind:'add',observation:'The neckline lacks a focal point.',action:'Add one compact necklace.',reason:'Creates deliberate emphasis.'}]}} onSuggestionFeedback={onFeedback}/>);expect(screen.getByText('Best next move')).toBeTruthy();expect(screen.getAllByText('Another option')).toHaveLength(2);fireEvent.press(screen.getByRole('button',{name:'Helpful, suggestion 1'}));await screen.findByText('Marked helpful');expect(screen.getByRole('button',{name:'Not for me, suggestion 2'})).toBeTruthy();expect(onFeedback).toHaveBeenCalledWith(0,true);});
