import React from 'react';
import {render,screen,fireEvent,waitFor} from '@testing-library/react-native';
const mockSubmit=jest.fn(),mockRefresh=jest.fn();
let mockBootstrap:unknown;
jest.mock('expo-router',()=>({router:{replace:jest.fn()}}));
jest.mock('../state/analysis-context',()=>({useAnalysis:()=>({state:{status:'ready',prepared:{uri:'file:///prepared.jpg'},prompt:'',error:null},setPrompt:jest.fn(),submit:mockSubmit,cancel:async()=>{}})}));
jest.mock('../state/session',()=>({useSession:()=>({bootstrap:mockBootstrap,error:null,refresh:mockRefresh})}));
import Review from '../../app/review';
it('allows an exempt test account even when the standard allowance is exhausted',()=>{mockBootstrap={consentAccepted:true,betaAccess:true,features:{outfit:true},remainingQuota:0,dailyQuotaExempt:true};render(<Review/>);expect(screen.getByText('Unlimited daily analyses · test account')).toBeTruthy();expect(screen.getByRole('button',{name:'Analyse outfit'})).toBeEnabled();});
beforeEach(()=>{jest.clearAllMocks();mockBootstrap={consentAccepted:true,betaAccess:true,features:{outfit:true},remainingQuota:2};mockRefresh.mockResolvedValue(undefined);});
it('allows another prepared outfit when allowance remains',()=>{render(<Review/>);expect(screen.getByRole('button',{name:'Analyse outfit'})).toBeEnabled();fireEvent.press(screen.getByRole('button',{name:'Analyse outfit'}));expect(mockSubmit).toHaveBeenCalledTimes(1);});
it('explains exhausted allowance and never submits',()=>{mockBootstrap={consentAccepted:true,betaAccess:true,features:{outfit:true},remainingQuota:0};render(<Review/>);expect(screen.getByText(/You have used all 3 daily analyses/)).toBeTruthy();expect(screen.getByRole('button',{name:'Analyse outfit'})).toBeDisabled();fireEvent.press(screen.getByRole('button',{name:'Analyse outfit'}));expect(mockSubmit).not.toHaveBeenCalled();});
it('recovers account access without resubmitting an assessment',async()=>{mockBootstrap=null;const view=render(<Review/>);expect(screen.getByRole('button',{name:'Analyse outfit'})).toBeDisabled();fireEvent.press(screen.getByRole('button',{name:'Refresh access'}));await waitFor(()=>expect(mockRefresh).toHaveBeenCalledTimes(1));mockBootstrap={consentAccepted:true,betaAccess:true,features:{outfit:true},remainingQuota:2};view.rerender(<Review/>);await waitFor(()=>expect(screen.getByRole('button',{name:'Analyse outfit'})).toBeEnabled());expect(mockSubmit).not.toHaveBeenCalled();});
