import {readFileSync,writeFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {z} from 'zod';
import {createHash} from 'node:crypto';
const base='supabase/functions/_shared/skills/';
const instructions=readFileSync(base+'outfit.md','utf8');
export const guidanceBudget=2000;
export function validateKnowledge(raw){
 const nonempty=z.string().trim().min(1);
 const catalogue=z.object({rubricVersion:nonempty,entries:z.array(z.object({topic:nonempty,text:nonempty,sourceIds:z.array(nonempty).min(1),reviewedAt:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}).strict()).min(1),sources:z.array(z.object({id:nonempty,title:nonempty,url:z.string().url().optional(),reviewStatus:nonempty,limitations:nonempty.optional()}).strict()).min(1)}).strict().parse(raw);
 const topics=new Set(catalogue.entries.map(e=>e.topic));
 const sources=new Set(catalogue.sources.map(s=>s.id));
 if(topics.size!==catalogue.entries.length||sources.size!==catalogue.sources.length)throw Error('Duplicate guidance identifiers');
 for(const topic of ['fit','proportion','balance','emphasis','rhythm','colour','texture','coherence','finishing','minimal_edits','trends'])if(!topics.has(topic))throw Error('Missing guidance topic: '+topic);
 for(const entry of catalogue.entries){
  if(entry.sourceIds.some(id=>!sources.has(id)))throw Error('Unknown guidance source');
  if(Buffer.byteLength(JSON.stringify(entry),'utf8')>guidanceBudget)throw Error('Guidance exceeds complete response budget: '+entry.topic);
 }
 return catalogue;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){
const knowledge=validateKnowledge(JSON.parse(readFileSync(base+'knowledge.json','utf8')));
const content=JSON.stringify({instructions,knowledge});
writeFileSync(base+'bundle.ts',`// Generated by npm run skills:build. Edit source Markdown/JSON.\nexport const outfitSkill = ${JSON.stringify({version:createHash('sha256').update(content).digest('hex'),instructions,knowledge},null,2)} as const;\n`);
}
