import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const base='supabase/functions/_shared/skills/';
const instructions=readFileSync(base+'outfit.md','utf8');
const knowledge=JSON.parse(readFileSync(base+'knowledge.json','utf8'));
const content=JSON.stringify({instructions,knowledge});
writeFileSync(base+'bundle.ts',`// Generated by npm run skills:build. Edit source Markdown/JSON.\nexport const outfitSkill = ${JSON.stringify({version:createHash('sha256').update(content).digest('hex'),instructions,knowledge},null,2)} as const;\n`);
